#!/usr/bin/python
#
# Select science windows that are well predicted by background tracers and
# that have only weak sources. Add them up for background cube production.

import os
import numpy as np
try:
    from astropy.io import fits
except ImportError:
    import pyfits as fits

from integral.isgri import bgcube

# Prefer prefixed paths when available for higher read performance
#
for attr in ('throng_dir', 'byscw_dir'):
    for prefix in (os.path.join('/tmp', os.environ['USER']), None):
        path = getattr(bgcube.cube, attr)
        if prefix:
            path_new = os.path.join(prefix, os.path.relpath(path, '/'))
            if os.path.isdir(path_new):
                setattr(bgcube.cube, attr, path_new)
            break

print('Loading from:')
print(bgcube.cube.throng_dir)
print(bgcube.cube.byscw_dir)

srcsig_pre = np.loadtxt('srcsig-predictable.log', usecols=(0,1))
sig_max = 20.0

idx_lowsrc = srcsig_pre[:, 1] <= sig_max
scw_lowsrc = srcsig_pre[idx_lowsrc, 0]

bgb = bgcube.BackgroundBuilder(scw_lowsrc)
bgcube = bgb.read_cubes()

hdu_pri = fits.PrimaryHDU()
hdu_cts = fits.ImageHDU(np.ma.filled(bgcube.counts, 0))
hdu_cts.header['EXTNAME'] = 'COUNTS'
hdu_eff = fits.ImageHDU(np.ma.filled(bgcube.efficiency, -1))
hdu_eff.header['EXTNAME'] = 'EXPOSURE'
for hdu in [hdu_cts, hdu_eff]:
    for keyword in ('duration', 'ontime'):
        hdu.header[keyword] = getattr(bgcube, keyword)
fitsfile = 'bgcube.fits'
hdulist = fits.HDUList([hdu_pri, hdu_cts, hdu_eff])
hdulist.writeto(fitsfile, clobber=True)
